// Package localmode contains the standalone CLI's local-mode contract.
package localmode

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os/exec"
	"strings"
)

const (
	dockerCommand       = "docker"
	serverContainerName = "volcano-server"
	serverBinaryPath    = "/app/volcano-hosting"
	redactedValue       = "<redacted>"
)

// Info is the local-mode metadata returned by the Volcano server container.
// It contains local credentials; avoid logging it directly. Accidental fmt
// output through String and GoString redacts secret-bearing fields.
type Info struct {
	APIURL                         string `json:"api_url"`
	ProjectID                      string `json:"project_id"`
	ProjectName                    string `json:"project_name"`
	UserID                         string `json:"user_id"`
	AuthUserID                     string `json:"auth_user_id"`
	AuthUserEmail                  string `json:"auth_user_email"`
	UserToken                      string `json:"user_token"`
	AnonKey                        string `json:"anon_key"`
	ServiceKey                     string `json:"service_key"`
	DefaultDatabaseName            string `json:"default_database_name"`
	DefaultDatabaseRegion          string `json:"default_database_region"`
	DefaultDatabasePostgresVersion string `json:"default_database_postgres_version"`
	DatabaseURL                    string `json:"database_url"`
	RedisURL                       string `json:"redis_url"`
	JWTSecret                      string `json:"jwt_secret"`
	EncryptionKey                  string `json:"encryption_key"`
	AnonKeySecret                  string `json:"anon_key_secret"`
	ServiceKeySecret               string `json:"service_key_secret"`
}

type redactedInfo Info

// String returns local-mode metadata with secret-bearing fields redacted.
func (i Info) String() string {
	return fmt.Sprintf("%+v", i.redacted())
}

// GoString returns local-mode metadata with secret-bearing fields redacted.
func (i Info) GoString() string {
	return fmt.Sprintf("%#v", i.redacted())
}

func (i Info) redacted() redactedInfo {
	redacted := redactedInfo(i)
	redacted.UserToken = redactedValue
	redacted.AnonKey = redactedValue
	redacted.ServiceKey = redactedValue
	redacted.DatabaseURL = redactedValue
	redacted.RedisURL = redactedValue
	redacted.JWTSecret = redactedValue
	redacted.EncryptionKey = redactedValue
	redacted.AnonKeySecret = redactedValue
	redacted.ServiceKeySecret = redactedValue
	return redacted
}

// CommandRunner runs an external command.
type CommandRunner interface {
	Run(ctx context.Context, name string, args ...string) ([]byte, error)
}

// CommandRunnerFunc adapts a function into a CommandRunner.
type CommandRunnerFunc func(ctx context.Context, name string, args ...string) ([]byte, error)

// Run executes f.
func (f CommandRunnerFunc) Run(ctx context.Context, name string, args ...string) ([]byte, error) {
	return f(ctx, name, args...)
}

type execCommandRunner struct{}

// FetchInfo returns local-mode metadata from the running Volcano server container.
// Callers should pass a context with a timeout.
func FetchInfo(ctx context.Context, runner CommandRunner) (Info, error) {
	if runner == nil {
		runner = execCommandRunner{}
	}

	output, err := runner.Run(ctx, dockerCommand, InfoCommandArgs()...)
	if err != nil {
		return Info{}, fmt.Errorf("failed to run local info command (is the volcano-server container running?): %w", err)
	}
	if strings.TrimSpace(string(output)) == "" {
		return Info{}, errors.New("local info command returned empty output")
	}

	var info Info
	if err := json.Unmarshal(output, &info); err != nil {
		return Info{}, fmt.Errorf("failed to parse local info output: %w", err)
	}
	return info, nil
}

// InfoCommandArgs returns the docker arguments used to fetch local-mode metadata.
func InfoCommandArgs() []string {
	return []string{
		"exec",
		serverContainerName,
		serverBinaryPath,
		"local",
		"info",
		"--format",
		"json",
	}
}

// PSQLCommandHint returns a POSIX-shell-safe psql invocation for the default local database.
func (i Info) PSQLCommandHint() string {
	return "psql " + shellQuote(i.DatabaseURL)
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}

func (execCommandRunner) Run(ctx context.Context, name string, args ...string) ([]byte, error) {
	if name != dockerCommand {
		return nil, fmt.Errorf("unsupported local mode command %q", name)
	}

	cmd := exec.CommandContext(ctx, dockerCommand, args...) //nolint:gosec // docker command and args are generated by FetchInfo/InfoCommandArgs.
	output, err := cmd.Output()
	if err == nil {
		return output, nil
	}

	var exitErr *exec.ExitError
	if errors.As(err, &exitErr) {
		stderr := strings.TrimSpace(string(exitErr.Stderr))
		if stderr != "" {
			return nil, fmt.Errorf("%s: %w", stderr, err)
		}
	}
	return nil, err
}
