name: Lint docs

on:
  pull_request:
    paths:
      - "docs/**"

permissions:
  contents: read

jobs:
  docs:
    uses: Kong/volcano-docs/.github/workflows/lint-docs.yml@06b40d8613779ad44bca0aceaca0d8f11bc25652 # main
    with:
      path: docs
