name: Lint docs

on:
  pull_request:
    paths:
      - "docs/**"

permissions:
  contents: read

jobs:
  docs:
    uses: Kong/volcano-docs/.github/workflows/lint-docs.yml@30a84228a943d2e194635a1dcdff4b185983a3df # main
    with:
      path: docs
